name: Trigger Jenkins Job on Dev Branch

on:
  push:
    branches:
      - dev  # Kích hoạt khi có thay đổi ở nhánh dev

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Jenkins Job Remotely
        run: |
          curl -X POST "${{ secrets.JENKINS_URL_2 }}/job/${{ secrets.JENKINS_JOB_NAME_2 }}/buildWithParameters?token=${{ secrets.JENKINS_JOB_TOKEN_2 }}" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
          --data-urlencode "BRANCH=dev-frontend"
